# Generated by Django 5.0.4 on 2024-10-21 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('mobile', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('split_method', models.CharField(choices=[('Equal', 'Equal'), ('Exact', 'Exact'), ('Percentage', 'Percentage')], max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('creators', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='app.client')),
                ('participants', models.ManyToManyField(related_name='sharing_expenses', to='app.client')),
            ],
        ),
    ]
