# Generated by Django 5.0.4 on 2024-10-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='split_method',
            field=models.CharField(choices=[('equal', 'Equal split'), ('exact', 'Exact split'), ('percentage', 'Percentage split')], max_length=15),
        ),
    ]
