# Generated by Django 5.0.4 on 2024-10-21 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_expenses_split_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_owed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_details', to='app.expenses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_details', to='app.client')),
            ],
        ),
    ]
